import type { Project } from './types'

export const initialProject: Project = {
  id: '1',
  title: 'Untitled Project',
  scenes: [
    {
      id: 'scene-1',
      title: 'Coffee Shop',
      location: 'Coffee Shop',
      time: 'Day',
      characters: ['Anna', 'Mark'],
      description: 'Anna and Mark meet for the first time.',
      mood: ['Warm', 'Hopeful'],
      order: 0,
      isActive: true,
      blocks: [
        {
          id: 'block-1',
          type: 'action',
          content: 'Anna sits at a corner table, nervously stirring her coffee. The morning light streams through the window.',
          order: 0,
        },
        {
          id: 'block-2',
          type: 'dialogue',
          content: 'Is this seat taken?',
          characterName: 'MARK',
          order: 1,
        },
        {
          id: 'block-3',
          type: 'dialogue',
          content: 'No, please. Sit down.',
          characterName: 'ANNA',
          order: 2,
        },
        {
          id: 'block-4',
          type: 'ambience',
          content: 'Soft jazz playing in the background',
          order: 3,
        },
      ],
    },
    {
      id: 'scene-2',
      title: 'Phone Call',
      location: 'Anna\'s Apartment',
      time: 'Evening',
      characters: ['Anna'],
      description: 'Anna receives a troubling phone call.',
      mood: ['Tense', 'Uncertain'],
      order: 1,
      isActive: true,
      blocks: [
        {
          id: 'block-5',
          type: 'action',
          content: 'Anna paces back and forth in her small apartment, phone pressed to her ear.',
          order: 0,
        },
        {
          id: 'block-6',
          type: 'dialogue',
          content: 'What do you mean he\'s leaving?',
          characterName: 'ANNA',
          order: 1,
        },
        {
          id: 'block-7',
          type: 'pause',
          content: '',
          order: 2,
        },
        {
          id: 'block-8',
          type: 'dialogue',
          content: 'When? Tonight?',
          characterName: 'ANNA',
          order: 3,
        },
      ],
    },
    {
      id: 'scene-3',
      title: 'Train Station',
      location: 'Train Station',
      time: 'Night',
      characters: ['Anna', 'Mark'],
      description: 'Anna confronts Mark before he leaves town.',
      mood: ['Rain', 'Tension', 'Silence'],
      order: 2,
      isActive: true,
      blocks: [
        {
          id: 'block-9',
          type: 'ambience',
          content: 'Rain falling on the platform',
          order: 0,
        },
        {
          id: 'block-10',
          type: 'action',
          content: 'Anna runs across the train platform looking for Mark.',
          order: 1,
        },
        {
          id: 'block-11',
          type: 'action',
          content: 'She spots him near the edge, bag in hand, staring at the tracks.',
          order: 2,
        },
        {
          id: 'block-12',
          type: 'dialogue',
          content: 'Where are you going?',
          characterName: 'ANNA',
          order: 3,
        },
        {
          id: 'block-13',
          type: 'dialogue',
          content: 'Somewhere you can\'t follow.',
          characterName: 'MARK',
          order: 4,
        },
        {
          id: 'block-14',
          type: 'pause',
          content: '',
          order: 5,
        },
        {
          id: 'block-15',
          type: 'note',
          content: 'Consider adding flashback here to show their first meeting',
          order: 6,
        },
      ],
    },
    {
      id: 'scene-4',
      title: 'Final Confrontation',
      location: 'Train Platform',
      time: 'Night',
      characters: ['Anna', 'Mark'],
      description: 'The emotional climax of the story.',
      mood: ['Desperation', 'Love', 'Loss'],
      order: 3,
      isActive: true,
      blocks: [
        {
          id: 'block-16',
          type: 'action',
          content: 'The train whistle blows in the distance. Mark turns to face Anna.',
          order: 0,
        },
        {
          id: 'block-17',
          type: 'dialogue',
          content: 'You never understood, did you?',
          characterName: 'MARK',
          order: 1,
        },
        {
          id: 'block-18',
          type: 'dialogue',
          content: 'Then help me understand. Please.',
          characterName: 'ANNA',
          order: 2,
        },
        {
          id: 'block-19',
          type: 'ambience',
          content: 'Thunder rolls in the distance',
          order: 3,
        },
      ],
    },
  ],
}
